## Ejercicio 1

1. Registre: x̄ = 52, σ = 8, n = 36, nivel de confianza 95%



In [1]:
import numpy as np
from scipy.stats import norm

# Datos
x_bar = 52
sigma = 8
n = 36
confianza = 0.95


2. Calcule error estándar: 8 / √36 = 1.33

In [2]:
# Error estándar
SE = sigma / np.sqrt(n)
SE

np.float64(1.3333333333333333)

3. Valor crítico Zα/2 para 95% = 1.96

In [3]:
# Valor crítico Z
z_critico = norm.ppf(1 - (1 - confianza)/2)
z_critico

np.float64(1.959963984540054)

4. Calcule margen de error: 1.96 × 1.33 ≈ 2.61

In [4]:
# Margen de error
ME = z_critico * SE
ME

np.float64(2.613285312720072)

5. Intervalo: 52 ± 2.61 → (49.39, 54.61)

In [5]:
# Intervalo
lim_inf = x_bar - ME
lim_sup = x_bar + ME

lim_inf, lim_sup

(np.float64(49.38671468727993), np.float64(54.61328531272007))

6. Intérprete: con 95% de confianza, la media poblacional está entre 49.39 y 54.61 horas

In [6]:
print(f"Error estándar: {SE:.4f}")
print(f"Valor crítico Z: {z_critico:.2f}")
print(f"Margen de error: {ME:.4f}")
print(f"Intervalo de confianza 95%: ({lim_inf:.2f}, {lim_sup:.2f})")

Error estándar: 1.3333
Valor crítico Z: 1.96
Margen de error: 2.6133
Intervalo de confianza 95%: (49.39, 54.61)


Con un 95% de confianza, la duración media real de las baterías en la población está entre 49.39 y 54.61 horas.

Dicho de otra manera —y esto suele ser lo que realmente importa entender— si repitiéramos el proceso de tomar muestras de 36 baterías muchas veces y construyéramos un intervalo cada vez, aproximadamente el 95% de esos intervalos incluiría la verdadera media poblacional.

No significa que haya 95% de probabilidad de que la media esté ahí (la media es fija). Lo que tiene el 95% de “confianza” es el procedimiento.

En términos prácticos: la empresa puede esperar que la duración promedio real esté alrededor de 52 horas, con una variación plausible de ±2.61 horas.

## Ejercicio 2

1. Identifique qué datos tienes y con qué tipo de fórmula estás trabajando.
* ¿Se conoce la desviación estándar poblacional? Si no, vas a usar t-Student.
* Anote: tamaño de muestra, media muestral, desviación muestral y nivel de confianza.



Como no se conoce σ (tenemos s), corresponde t de Student con grados de libertad = n -1 = 24

In [7]:
import numpy as np
from scipy.stats import t

# Datos
x_bar = 42
s = 6
n = 25

# Grados de libertad
gl = n - 1

2. Calcule el error estándar de la media.
* Recuerde: el error estándar se obtiene dividiendo la desviación muestral por la raíz cuadrada del tamaño de muestra.
* Use una calculadora o Python si lo necesitás.


In [8]:
# Error estándar
SE = s / np.sqrt(n)
SE

np.float64(1.2)

3. Busque el valor crítico t correspondiente.
* Necesita el valor t para un 99% de confianza y 24 grados de libertad (n-1).
* Use una tabla t o una función estadística como scipy.stats.t.ppf.


In [9]:
confianza = 0.99

# Valor crítico t
alpha = 1 - confianza
t_critico = t.ppf(1 - alpha/2, gl)

t_critico

np.float64(2.796939504774456)

4. Construye el intervalo usando la fórmula general.
* Intervalo = media ± (t * error estándar)
* No resuelvas el número aún. Observe cómo el valor t es más alto cuanto mayor es la confianza.


In [10]:
# Margen de error
ME = t_critico * SE

# Intervalo
lim_inf = x_bar - ME
lim_sup = x_bar + ME

print(f"Margen de error: {ME:.4f}")
print(f"IC 99%: ({lim_inf:.2f}, {lim_sup:.2f})")

Margen de error: 3.3563
IC 99%: (38.64, 45.36)


5. Interprete el resultado.
* ¿Está 45 minutos fuera del intervalo? Si sí, entonces puedes afirmar con 99% de confianza que la media es menor a 45 minutos.
* Si 45 está dentro del intervalo, no se puede afirmar con seguridad que sea menor.

In [11]:
import numpy as np
from scipy.stats import t

x_bar, s, n = 42, 6, 25
mu0 = 45
df = n - 1

se = s / np.sqrt(n)
t_stat = (x_bar - mu0) / se
p_unilateral = t.cdf(t_stat, df)  # cola izquierda

print("t =", t_stat)
print("p-value unilateral =", p_unilateral)
print("¿Rechazo H0 al 1%? (alpha=0.01):", p_unilateral < 0.01)


t = -2.5
p-value unilateral = 0.009827087558289392
¿Rechazo H0 al 1%? (alpha=0.01): True


In [12]:
conf_unilateral = 0.99
t_crit_1s = t.ppf(conf_unilateral, df)  # cuantil 0.99 (una cola)
upper_bound = x_bar + t_crit_1s * se

print("t crítico (1 cola, 99%):", t_crit_1s)
print("Límite superior 99% unilateral:", upper_bound)
print("¿Upper bound < 45?:", upper_bound < 45)


t crítico (1 cola, 99%): 2.492159473157756
Límite superior 99% unilateral: 44.99059136778931
¿Upper bound < 45?: True
